# Generated by Django 5.2.6 on 2025-09-18 21:22

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('store_type', models.TextField(blank=True, choices=[('clothing', 'Apparel&Accessories'), ('electronics', 'Electronics&Accessories'), ('food', 'Food&Bevarages'), ('beauty', 'Health&Beauty'), ('games', 'Hobby,Toys&Games'), ('library', 'Books,Music&Media'), ('jewelry', 'Jewelry&Luxury goods')], default='electronics', help_text='Please provide the type of store you are creating', max_length=100)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='store_case_insentive_unique', violation_error_message='A store with the name exists')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('available', models.BooleanField(default=False)),
                ('store', models.ForeignKey(help_text='You must provide a store that uploaded this product', on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
    ]
