# Generated by Django 5.2.6 on 2025-09-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ManyToManyField(help_text='Please provide a store for this product', to='store.store'),
        ),
    ]
